### ISSUE TITLE
edit_path helper doesn't combine well with other path helpers as an argument

### ISSUE THREAD

**Issue by jfeaver** [code-and-effect/effective_regions#5]
There's a double slash in the url/path where there shouldn't be.

```
effective_regions.edit_url(chapter_path(@chapter))
#=> http://localhost:3000/edit//chapters/foo-1
```

**Comment by jfeaver** [comment]
I looked into this for a bit and there's no easy solution.  I didn't realize, at first, that the `edit_path` and `edit_url` helpers are provided by Rails.  There's an option to add a trailing slash but no option to remove a leading slash.

A quick solution to this is to manually remove the leading slash:

```
effective_regions.edit_path(chapter_path(@chapter).slice(1..-1))
```

**Comment by matt-riemer** [comment]
It all works, but there's also a technically not correct issue with  passing a path like `chapter_path(@chapter, some: 'thing')` and combining with `exit: /`
